<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.treblereel.j2cl.plugin.tests</groupId>
        <artifactId>hello-world-reactor</artifactId>
        <version>0.24</version>
    </parent>

    <artifactId>hello-world-reactor-app</artifactId>
    <name>Test: Hello World Reactor - App</name>
    <description>Application module consuming reactor library</description>

    <dependencies>
        <dependency>
            <groupId>org.treblereel.j2cl.plugin.tests</groupId>
            <artifactId>hello-world-reactor-lib</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.treblereel.j2cl.plugin</groupId>
                <artifactId>j2cl-maven-plugin</artifactId>
                <version>0.24</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
