<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.treblereel.j2cl.plugin.tests</groupId>
        <artifactId>j2cl-plugin-tests</artifactId>
        <version>0.24</version>
    </parent>

    <artifactId>hello-world-gwt-super-source</artifactId>
    <name>Test: GWT Super Source Emulation</name>
    <description>GWT-style super-source with emulated JDK classes</description>

    <dependencies>
        <dependency>
            <groupId>com.google.jsinterop</groupId>
            <artifactId>jsinterop-annotations</artifactId>
            <version>2.1.0</version>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>**/emul/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.treblereel.j2cl.plugin</groupId>
                <artifactId>j2cl-maven-plugin</artifactId>
                <version>0.24</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <compilationLevel>ADVANCED</compilationLevel>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
