<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.treblereel.j2cl.plugin.samples</groupId>
        <artifactId>multi-module-sample</artifactId>
        <version>0.24</version>
    </parent>

    <artifactId>multi-module-sample-app</artifactId>
    <name>Sample: Multi-Module - App</name>

    <dependencies>
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-dom</artifactId>
        </dependency>
        <dependency>
            <groupId>org.treblereel.j2cl.processors</groupId>
            <artifactId>annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.treblereel.j2cl.plugin.samples</groupId>
            <artifactId>multi-module-sample-lib</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.treblereel.j2cl.plugin</groupId>
                <artifactId>j2cl-maven-plugin</artifactId>
                <version>0.24</version>
                <configuration>
                    <compilationLevel>BUNDLE_JAR</compilationLevel>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.treblereel.j2cl.processors</groupId>
                            <artifactId>processors</artifactId>
                            <version>0.10</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
