<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.treblereel.j2cl.plugin</groupId>
        <artifactId>parent</artifactId>
        <version>0.24</version>
    </parent>

    <groupId>org.treblereel.j2cl.plugin.samples</groupId>
    <artifactId>j2cl-plugin-samples</artifactId>
    <packaging>pom</packaging>
    <name>J2CL Plugin Samples</name>

    <modules>
        <module>single-module</module>
        <module>multi-module</module>
        <module>wasm-jsinterop</module>
    </modules>
</project>
